import type { RuroConfig } from "../config.js";
import type { StatusTransition } from "../history/transitions.js";
import type { RepoStatus, RuroReport, ScoredRepo } from "../types.js";

function relativeDays(iso: string | null): string {
  if (!iso) return "—";
  const days = Math.floor(
    (Date.now() - new Date(iso).getTime()) / 86_400_000,
  );
  if (days <= 0) return "today";
  if (days === 1) return "1d ago";
  if (days < 30) return `${days}d ago`;
  if (days < 365) return `${Math.floor(days / 30)}mo ago`;
  return `${Math.floor(days / 365)}y ago`;
}

function esc(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function statusCounts(repos: ScoredRepo[]): Record<RepoStatus, number> {
  const counts: Record<RepoStatus, number> = {
    LIVE: 0,
    ACTIVE: 0,
    STALE: 0,
    DORMANT: 0,
    DEAD: 0,
    ARCHIVED: 0,
  };
  for (const r of repos) counts[r.status] += 1;
  return counts;
}

export function buildReport(
  config: RuroConfig,
  repos: ScoredRepo[],
  excludedCount: number,
  transitions: StatusTransition[] = [],
): RuroReport {
  const visible =
    config.privacy.mode === "public_only_render"
      ? repos.filter((r) => !r.signals.isPrivate)
      : repos;

  return {
    schema_version: 1,
    generated_at: new Date().toISOString(),
    owner: config.owner,
    repo_count: repos.length + excludedCount,
    included_count: visible.length,
    excluded_count: excludedCount + (repos.length - visible.length),
    status_counts: statusCounts(visible),
    weights: { ...config.weights },
    repos: visible,
    transitions,
  };
}

export function renderDashboard(report: RuroReport, config: RuroConfig): string {
  const top = report.repos.slice(0, 3);
  const counts = Object.entries(report.status_counts)
    .filter(([, n]) => n > 0)
    .map(([k, n]) => `**${k}** ${n}`)
    .join(" · ");

  const lines: string[] = [
    `# ${config.render.title}`,
    "",
    `> Generated by **Ruro** · ${report.generated_at} · owner \`${report.owner}\``,
    ">",
    "> Deterministic portfolio scorecard. Zero AI. Data never leaves GitHub.",
    "",
    "## Snapshot",
    "",
    `- Scanned / included / excluded: **${report.repo_count}** / **${report.included_count}** / **${report.excluded_count}**`,
    `- Weights: quality \`${report.weights.quality}\` · alive \`${report.weights.alive}\` · structure \`${report.weights.structure}\``,
    `- Status mix: ${counts || "—"}`,
    "",
    "## Top 3",
    "",
  ];

  if (top.length === 0) {
    lines.push("_No repositories scored._", "");
  } else {
    for (let i = 0; i < top.length; i += 1) {
      const r = top[i];
      lines.push(
        `${i + 1}. **[${r.signals.name}](${r.signals.url})** — \`${r.status}\` · score **${r.score}** · ${r.drivers.slice(0, 3).join(", ") || "—"}`,
      );
    }
    lines.push("");
  }

  lines.push("## Status changes", "");
  if (!report.transitions.length) {
    lines.push("_No status changes since the previous run._", "");
  } else {
    for (const t of report.transitions) {
      lines.push(
        `- **[${t.name}](${t.url})**: \`${t.from}\` → \`${t.to}\` (score ${t.scoreFrom} → ${t.scoreTo})`,
      );
    }
    lines.push("");
  }

  lines.push(
    "## All projects",
    "",
    "| Rank | Repo | Status | Score | Quality | Alive | Structure | Demo | Last push | Stack | Notes |",
    "| ---: | --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- |",
  );

  report.repos.forEach((r, idx) => {
    const notes = [
      ...r.drivers.slice(0, 2),
      ...r.blockers.slice(0, 2).map((b) => `!${b}`),
    ]
      .join(", ")
      .slice(0, 80);
    const stack = r.signals.primaryLanguage ?? "—";
    lines.push(
      `| ${idx + 1} | [${esc(r.signals.name)}](${r.signals.url}) | \`${r.status}\` | **${r.score}** | ${r.pillars.quality} | ${r.pillars.alive} | ${r.pillars.structure} | \`${r.signals.demo.status}\` | ${relativeDays(r.signals.pushedAt)} | ${esc(stack)} | ${esc(notes || "—")} |`,
    );
  });

  lines.push(
    "",
    "## Legend",
    "",
    "- **Score** = `0.40*Quality + 0.35*Alive + 0.25*Structure` (configurable)",
    "- **Status**: `LIVE` = verified deploy **and** push within `active_days` · `ACTIVE` recent without LIVE · `STALE`/`DORMANT` quiet · `DEAD` abandoned · `ARCHIVED`",
    "- **Demo**: `UP`/`DOWN`/`NONE`/`ERROR` from homepage probe (`verified` is separate from status)",
    "- Notes prefixed with `!` are blockers",
    "",
    "---",
    "_Ruro core is zero-AI. Same inputs ⇒ same scores. Copilot audit is optional judgment._",
    "",
  );

  return lines.join("\n");
}
